ui: mocha-bdd
browserify:
  - transform:
      name: babelify
browsers:
  - name: chrome
    version: -1..latest
  - name: firefox
    version: -1..latest
  - name: internet explorer
    version: 10..latest
  - name: android
    version: '4.4..latest'
  - name: safari
    version: 6..latest
  - name: iphone
    version: '8.0..latest'
